phraseapp:
  access_token: "d1d3d5065586ad8c44f020d9e7cfb7911de2e6b6d5a09db7861bf773d0df476b"
  project_id: "b96ade0110c0c94165260c51ebfc9b62"
  file_format: "properties"
  push:
    sources:
    - file: messages_en.properties
      params:
        update_translations: true
        locale_id: dc36a37db6f059be781e0e47bae30da0
    - file: messages_pl.properties
      params:
        update_translations: true
        locale_id: 3b691cd782233c04203706ff064a8dd5    
  pull:
    targets:
    - file: messages_en.properties
      params:
        update_translations: true
        locale_id: dc36a37db6f059be781e0e47bae30da0
    - file: messages_pl.properties
      params:
        update_translations: true
locale_id: 3b691cd782233c04203706ff064a8dd5    
